//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevsDNA.Application.Strings {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DevsDNA.Application.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AboutUsCEO {
            get {
                return ResourceManager.GetString("AboutUsCEO", resourceCulture);
            }
        }
        
        internal static string AboutUsCTO {
            get {
                return ResourceManager.GetString("AboutUsCTO", resourceCulture);
            }
        }
        
        internal static string AboutUsDescriptionBeatriz {
            get {
                return ResourceManager.GetString("AboutUsDescriptionBeatriz", resourceCulture);
            }
        }
        
        internal static string AboutUsDescriptionCiani {
            get {
                return ResourceManager.GetString("AboutUsDescriptionCiani", resourceCulture);
            }
        }
        
        internal static string AboutUsDescriptionJorge {
            get {
                return ResourceManager.GetString("AboutUsDescriptionJorge", resourceCulture);
            }
        }
        
        internal static string AboutUsDescriptionLuis {
            get {
                return ResourceManager.GetString("AboutUsDescriptionLuis", resourceCulture);
            }
        }
        
        internal static string AboutUsDescriptionMarco {
            get {
                return ResourceManager.GetString("AboutUsDescriptionMarco", resourceCulture);
            }
        }
        
        internal static string AboutUsDescriptionYeray {
            get {
                return ResourceManager.GetString("AboutUsDescriptionYeray", resourceCulture);
            }
        }
        
        internal static string AboutUsFunnyDescriptionBeatriz {
            get {
                return ResourceManager.GetString("AboutUsFunnyDescriptionBeatriz", resourceCulture);
            }
        }
        
        internal static string AboutUsFunnyDescriptionCiani {
            get {
                return ResourceManager.GetString("AboutUsFunnyDescriptionCiani", resourceCulture);
            }
        }
        
        internal static string AboutUsFunnyDescriptionJorge {
            get {
                return ResourceManager.GetString("AboutUsFunnyDescriptionJorge", resourceCulture);
            }
        }
        
        internal static string AboutUsFunnyDescriptionLuis {
            get {
                return ResourceManager.GetString("AboutUsFunnyDescriptionLuis", resourceCulture);
            }
        }
        
        internal static string AboutUsFunnyDescriptionMarco {
            get {
                return ResourceManager.GetString("AboutUsFunnyDescriptionMarco", resourceCulture);
            }
        }
        
        internal static string AboutUsFunnyDescriptionYeray {
            get {
                return ResourceManager.GetString("AboutUsFunnyDescriptionYeray", resourceCulture);
            }
        }
        
        internal static string AboutUsMobileDeveloper {
            get {
                return ResourceManager.GetString("AboutUsMobileDeveloper", resourceCulture);
            }
        }
        
        internal static string AboutUsMobileDeveloperSenior {
            get {
                return ResourceManager.GetString("AboutUsMobileDeveloperSenior", resourceCulture);
            }
        }
        
        internal static string AboutUsSubtitle {
            get {
                return ResourceManager.GetString("AboutUsSubtitle", resourceCulture);
            }
        }
        
        internal static string AboutUsTitle {
            get {
                return ResourceManager.GetString("AboutUsTitle", resourceCulture);
            }
        }
        
        internal static string AccessibleAboutUsButtonHelp {
            get {
                return ResourceManager.GetString("AccessibleAboutUsButtonHelp", resourceCulture);
            }
        }
        
        internal static string AccessibleBtnCallDevsDNA {
            get {
                return ResourceManager.GetString("AccessibleBtnCallDevsDNA", resourceCulture);
            }
        }
        
        internal static string AccessibleBtnClose {
            get {
                return ResourceManager.GetString("AccessibleBtnClose", resourceCulture);
            }
        }
        
        internal static string AccessibleBtnCloseNewsHelp {
            get {
                return ResourceManager.GetString("AccessibleBtnCloseNewsHelp", resourceCulture);
            }
        }
        
        internal static string AccessibleBtnClosePostHelp {
            get {
                return ResourceManager.GetString("AccessibleBtnClosePostHelp", resourceCulture);
            }
        }
        
        internal static string AccessibleBtnCloseVideoHelp {
            get {
                return ResourceManager.GetString("AccessibleBtnCloseVideoHelp", resourceCulture);
            }
        }
        
        internal static string AccessibleBtnMailDevsDNA {
            get {
                return ResourceManager.GetString("AccessibleBtnMailDevsDNA", resourceCulture);
            }
        }
        
        internal static string AccessibleBtnMainActions {
            get {
                return ResourceManager.GetString("AccessibleBtnMainActions", resourceCulture);
            }
        }
        
        internal static string AccessibleBtnMainActionsHelp {
            get {
                return ResourceManager.GetString("AccessibleBtnMainActionsHelp", resourceCulture);
            }
        }
        
        internal static string AccessibleBtnOpenFacebookDevsDNA {
            get {
                return ResourceManager.GetString("AccessibleBtnOpenFacebookDevsDNA", resourceCulture);
            }
        }
        
        internal static string AccessibleBtnOpenInstagramDevsDNA {
            get {
                return ResourceManager.GetString("AccessibleBtnOpenInstagramDevsDNA", resourceCulture);
            }
        }
        
        internal static string AccessibleBtnOpenLinkedinDevsDNA {
            get {
                return ResourceManager.GetString("AccessibleBtnOpenLinkedinDevsDNA", resourceCulture);
            }
        }
        
        internal static string AccessibleBtnOpenPost {
            get {
                return ResourceManager.GetString("AccessibleBtnOpenPost", resourceCulture);
            }
        }
        
        internal static string AccessibleBtnOpenPostHelp {
            get {
                return ResourceManager.GetString("AccessibleBtnOpenPostHelp", resourceCulture);
            }
        }
        
        internal static string AccessibleBtnOpenTwitterDevsDNA {
            get {
                return ResourceManager.GetString("AccessibleBtnOpenTwitterDevsDNA", resourceCulture);
            }
        }
        
        internal static string AccessibleBtnPlayVideo {
            get {
                return ResourceManager.GetString("AccessibleBtnPlayVideo", resourceCulture);
            }
        }
        
        internal static string AccessibleBtnPlayVideoHelp {
            get {
                return ResourceManager.GetString("AccessibleBtnPlayVideoHelp", resourceCulture);
            }
        }
        
        internal static string AccessibleBtnShare {
            get {
                return ResourceManager.GetString("AccessibleBtnShare", resourceCulture);
            }
        }
        
        internal static string AccessibleBtnShareDevsDNAApp {
            get {
                return ResourceManager.GetString("AccessibleBtnShareDevsDNAApp", resourceCulture);
            }
        }
        
        internal static string AccessibleBtnShareNewsHelp {
            get {
                return ResourceManager.GetString("AccessibleBtnShareNewsHelp", resourceCulture);
            }
        }
        
        internal static string AccessibleBtnShareVideoHelp {
            get {
                return ResourceManager.GetString("AccessibleBtnShareVideoHelp", resourceCulture);
            }
        }
        
        internal static string AccessibleDoubleTapNewsDetail {
            get {
                return ResourceManager.GetString("AccessibleDoubleTapNewsDetail", resourceCulture);
            }
        }
        
        internal static string AccessibleDoubleTapVideoDetail {
            get {
                return ResourceManager.GetString("AccessibleDoubleTapVideoDetail", resourceCulture);
            }
        }
        
        internal static string AccessibleNewButtonHelp {
            get {
                return ResourceManager.GetString("AccessibleNewButtonHelp", resourceCulture);
            }
        }
        
        internal static string AccessibleNewsCarouselHelp {
            get {
                return ResourceManager.GetString("AccessibleNewsCarouselHelp", resourceCulture);
            }
        }
        
        internal static string AccessibleNewsCarouselName {
            get {
                return ResourceManager.GetString("AccessibleNewsCarouselName", resourceCulture);
            }
        }
        
        internal static string AccessibleRRSSButtonHelp {
            get {
                return ResourceManager.GetString("AccessibleRRSSButtonHelp", resourceCulture);
            }
        }
        
        internal static string AccessibleRRSSCollectionHelp {
            get {
                return ResourceManager.GetString("AccessibleRRSSCollectionHelp", resourceCulture);
            }
        }
        
        internal static string AccessibleRRSSCollectionName {
            get {
                return ResourceManager.GetString("AccessibleRRSSCollectionName", resourceCulture);
            }
        }
        
        internal static string AccessibleVideosButtonHelp {
            get {
                return ResourceManager.GetString("AccessibleVideosButtonHelp", resourceCulture);
            }
        }
        
        internal static string AccessibleVideosCarouselHelp {
            get {
                return ResourceManager.GetString("AccessibleVideosCarouselHelp", resourceCulture);
            }
        }
        
        internal static string AccessibleVideosCarouselName {
            get {
                return ResourceManager.GetString("AccessibleVideosCarouselName", resourceCulture);
            }
        }
        
        internal static string AlertCheckConnectionAgain {
            get {
                return ResourceManager.GetString("AlertCheckConnectionAgain", resourceCulture);
            }
        }
        
        internal static string AlertError {
            get {
                return ResourceManager.GetString("AlertError", resourceCulture);
            }
        }
        
        internal static string AlertErrorCheckingConnection {
            get {
                return ResourceManager.GetString("AlertErrorCheckingConnection", resourceCulture);
            }
        }
        
        internal static string AlertIWantKeepGoing {
            get {
                return ResourceManager.GetString("AlertIWantKeepGoing", resourceCulture);
            }
        }
        
        internal static string AlertMailNotSupported {
            get {
                return ResourceManager.GetString("AlertMailNotSupported", resourceCulture);
            }
        }
        
        internal static string AlertNo {
            get {
                return ResourceManager.GetString("AlertNo", resourceCulture);
            }
        }
        
        internal static string AlertNoConnectivity {
            get {
                return ResourceManager.GetString("AlertNoConnectivity", resourceCulture);
            }
        }
        
        internal static string AlertNotificationText {
            get {
                return ResourceManager.GetString("AlertNotificationText", resourceCulture);
            }
        }
        
        internal static string AlertNotificationTitle {
            get {
                return ResourceManager.GetString("AlertNotificationTitle", resourceCulture);
            }
        }
        
        internal static string AlertOk {
            get {
                return ResourceManager.GetString("AlertOk", resourceCulture);
            }
        }
        
        internal static string AlertPhoneDialerNotSupported {
            get {
                return ResourceManager.GetString("AlertPhoneDialerNotSupported", resourceCulture);
            }
        }
        
        internal static string AlertPoorConnectivity {
            get {
                return ResourceManager.GetString("AlertPoorConnectivity", resourceCulture);
            }
        }
        
        internal static string AlertSure {
            get {
                return ResourceManager.GetString("AlertSure", resourceCulture);
            }
        }
        
        internal static string AlertUnexpectedError {
            get {
                return ResourceManager.GetString("AlertUnexpectedError", resourceCulture);
            }
        }
        
        internal static string AlertYeah {
            get {
                return ResourceManager.GetString("AlertYeah", resourceCulture);
            }
        }
        
        internal static string AlertYes {
            get {
                return ResourceManager.GetString("AlertYes", resourceCulture);
            }
        }
        
        internal static string ButtonFanMailSubject {
            get {
                return ResourceManager.GetString("ButtonFanMailSubject", resourceCulture);
            }
        }
        
        internal static string ButtonFanMailText {
            get {
                return ResourceManager.GetString("ButtonFanMailText", resourceCulture);
            }
        }
        
        internal static string ButtonFanShareTitle {
            get {
                return ResourceManager.GetString("ButtonFanShareTitle", resourceCulture);
            }
        }
        
        internal static string MainAboutUs {
            get {
                return ResourceManager.GetString("MainAboutUs", resourceCulture);
            }
        }
        
        internal static string MainNewButton {
            get {
                return ResourceManager.GetString("MainNewButton", resourceCulture);
            }
        }
        
        internal static string MainSocialNetworkAccesibleText {
            get {
                return ResourceManager.GetString("MainSocialNetworkAccesibleText", resourceCulture);
            }
        }
        
        internal static string MainSocialNetworkButton {
            get {
                return ResourceManager.GetString("MainSocialNetworkButton", resourceCulture);
            }
        }
        
        internal static string MainVideosButton {
            get {
                return ResourceManager.GetString("MainVideosButton", resourceCulture);
            }
        }
        
        internal static string SocialNetworkPostAccount {
            get {
                return ResourceManager.GetString("SocialNetworkPostAccount", resourceCulture);
            }
        }
        
        internal static string SocialNetworkPostAuthor {
            get {
                return ResourceManager.GetString("SocialNetworkPostAuthor", resourceCulture);
            }
        }
        
        internal static string SplashSlogan {
            get {
                return ResourceManager.GetString("SplashSlogan", resourceCulture);
            }
        }
        
        internal static string SplashStart {
            get {
                return ResourceManager.GetString("SplashStart", resourceCulture);
            }
        }
        
        internal static string AccessibleBtnShareVideo {
            get {
                return ResourceManager.GetString("AccessibleBtnShareVideo", resourceCulture);
            }
        }
        
        internal static string AccessibleAboutUsSubtitle {
            get {
                return ResourceManager.GetString("AccessibleAboutUsSubtitle", resourceCulture);
            }
        }
        
        internal static string AccessibleSplashSlogan {
            get {
                return ResourceManager.GetString("AccessibleSplashSlogan", resourceCulture);
            }
        }
    }
}
